[workspace]
members = ["swc-plugin-css-variable", "transform"]
resolver = "2"

[profile.release]
# This profile results in small binary size with acceptable impact on
# performance, but there may well be further optimizations to be had.
strip = "debuginfo"
codegen-units = 1
lto = true
opt-level = "z"
