name: docs

on:
  push:
    branches:
      - main 
    paths:
      - 'docs/**'

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: RustUp
      run: rustup target add wasm32-wasi
    - run: npm install
    - run: npm run prepublishOnly
      env:
        CI: true
    - run: npm run docs
    - name: Deploy 
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/out