name: SWC validation

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: Rust tests & lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Enable caching
        uses: Swatinem/rust-cache@v1
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  # cross-os:
  #   strategy:
  #     matrix:
  #       node-version: [16]
  #       os: [ubuntu-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: RustUp
  #       run: rustup target add wasm32-wasi
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with: ${{ matrix.node-version }}
  #     - name: Install NPM Dependencies
  #       run: npm i
  #     - name: Build JS
  #       run: npm run build
  #     - name: Build SWC RUST Plugin
  #       run: npm run build:swc
  #     - name: Run tests
  #       run: npm run test:swc
