name: SWC validation

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: Rust tests & lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: swc
      - name: Run cargo check
        run: cargo check --manifest-path swc/Cargo.toml
      - name: Run cargo test
        run: cargo test --manifest-path swc/Cargo.toml
      - name: Run cargo fmt
        run: cargo fmt --manifest-path swc/Cargo.toml --all -- --check
      - name: Run cargo clippy
        run: cargo clippy --manifest-path swc/Cargo.toml -- -D warnings

  wasm:
    name: Wasm plugin tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Add wasm32-wasip1 target
        run: rustup target add wasm32-wasip1
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: swc
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install NPM dependencies
        run: npm i
      - name: Build JS
        run: npm run build
      - name: Build SWC plugin
        run: npm run build:swc
      - name: Run tests
        run: npm run test:swc:jest
